#apiVersion: v1
#kind: Service
#metadata:
#  name: bootcamp-product-service
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 80
#      targetPort: 8080
#  selector:
#    app: bootcamp-product-service